# Generated by Django 4.0 on 2021-12-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre Departamento')),
                ('nombre_encargado', models.CharField(max_length=250, verbose_name='Nombre Encargado')),
                ('correo', models.CharField(max_length=250, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre Proveedor')),
                ('correo', models.CharField(max_length=250, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre Producto')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('descripción', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('iva', models.FloatField(default=0, verbose_name='IVA')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de orden')),
                ('condiciones', models.CharField(max_length=250, verbose_name='Condiciones')),
                ('estatus', models.BooleanField(default=True)),
                ('idDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(default=0, verbose_name='Cantidad de Productos')),
                ('descripción', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.orden')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.producto')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
