# Generated by Django 4.0 on 2022-01-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='firma',
            field=models.CharField(default='', max_length=50, verbose_name='Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='observacion',
            field=models.CharField(default='', max_length=200, verbose_name='Observaciones'),
            preserve_default=False,
        ),
    ]
