# Generated by Django 4.0 on 2022-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orden_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idSolicitud',
            field=models.PositiveIntegerField(default=0, verbose_name='Solicitud'),
        ),
    ]
