# Generated by Django 4.0 on 2022-01-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orden_idsolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idProveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.proveedor'),
            preserve_default=False,
        ),
    ]
